# Generated by Django 5.0 on 2026-09-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registration'), ('REVIEW_CREATED', 'Review created'), ('MOVIE_CHECKED', 'Movie checked'), ('COMMENT_CREATED', 'Comment created'), ('LIKE_ADDED', 'Like added'), ('LIKE_REMOVED', 'Like removed'), ('CLUB_CREATED', 'Club created'), ('CLUB_JOINED', 'Club joined'), ('CLUB_LEFT', 'Club left'), ('WATCHLIST_ADDED', 'Added to watchlist'), ('WATCHLIST_REMOVED', 'Removed from watchlist')], max_length=32),
        ),
    ]
